site_name: Lancer Shield Docs
site_url: https://lancershield.github.io/docs/
strict: true
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en
  # Remove comments above palette blocks
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Overview: index.md
  - Severity Framework: severity-framework/index.md
  - Vulnerability Database:
      - Overview: vuln-db/index.md
      - Template: vuln-db/template.md
      - Critical:
          - Overview: vuln-db/critical/index.md
          - Price-Oracle: vuln-db/critical/Price-oracle.md
          - Flash-Loan-Attack: vuln-db/critical/Flash-Loan-Attacks.md
          - Arbitrary Storage: vuln-db/critical/Arbitrary-Storage.md
          - Improperly Initialized: vuln-db/critical/Improperly-Initialized.md
          - Liquidity Rug: vuln-db/critical/Liquidity-Rug.md
          - Treasury Drain: vuln-db/critical/Treasury-Drain.md
          - Backdoor Functionality: vuln-db/critical/Backdoor-Functionality.md
          - Untrusted delegatecall: vuln-db/critical/Untrusted-delegatecall.md
          - Classic Reentrancy: vuln-db/critical/Classic-Reentrancy.md
          - Contract Destructible: vuln-db/critical/Contract-Destructible.md
          - Batch Reentrancy: vuln-db/critical/Batch-Reentrancy.md
          - LayerZero Trusted: vuln-db/critical/LayerZero-Trusted.md
          - Unintended Reentrancy: vuln-db/critical/Unintended-Reentrancy.md
          - Insecure executeTransaction: vuln-db/critical/Insecure-executeTransaction.md
          - Unrestricted Withdrawals: vuln-db/critical/Unrestricted-Withdrawals.md
          - Access Control: vuln-db/critical/Access-Control.md
          - Arbitrary from in transferFrom: vuln-db/critical/Arbitrary-from.md
          - Insufficient Signature Verification: vuln-db/critical/Insufficient.md
          - Misconfigured Role-Based: vuln-db/critical/Misconfigured.md
          - Oracle Feed Delay Exploits: vuln-db/critical/Oracle-Feed-Delay-Exploits.md
      - High:
          - Overview: vuln-db/high/index.md
          - Denial of Service: vuln-db/high/denial-of-service.md
          - Improper-Upgrade: vuln-db/high/Improper-Upgradeability.md
          - Insecure-Randomness: vuln-db/high/Insecure-Randomness.md
          - Ownership-Vulnerability: vuln-db/high/Ownership.md
          - Cross-Contract: vuln-db/high/cross-contract.md
          - Blockhash Dependence: vuln-db/high/Blockhash-Dependence.md
          - merkle-proof: vuln-db/high/Merkle-proof.md
          - Async Withdraw: vuln-db/high/Async Withdraw.md
          - Reward Inflation: vuln-db/high/Reward Inflation.md
          - Upgrade Bricking: vuln-db/high/Upgrade-Bricking.md
          - Emergency Function Abuse: vuln-db/high/Emergency-Function-Abuse.md
          - Internal Accounting Drift: vuln-db/high/Internal-Accounting-Drif.md
          - Faulty Permit: vuln-db/high/Faulty-Permit.md
          - Counter Overflow: vuln-db/high/Counter-Overflow.md
          - Stale Price: vuln-db/high/Stale-Price.md
          - Unsafe tx.origin: vuln-db/high/Unsafe-tx.origin.md
          - Unchecked Slippage: vuln-db/high/Unchecked-Slippage.md
          - Ignoring ChainID: vuln-db/high/Ignoring-ChainID.md
          - Transfer Hook Abuse: vuln-db/high/Transfer-Hook-Abuse.md
          - Flawed Migration: vuln-db/high/Flawed-Migration.md
          - Front-Running NFT: vuln-db/high/Front-Running-NFT.md
          - NFT Metadata Tampering: vuln-db/high/NFT-Metadata-Tampering.md
          - Vesting Shortcut Exploits: vuln-db/high/Vesting.md
          - Flawed Slashing: vuln-db/high/Flawed-Slashing.md
          - Whitelist Bypass: vuln-db/high/Whitelist-Bypass.md
          - Unsustainable Pump and Dump: vuln-db/high/Unsustainable.md
          - Vote Escrow Exploits: vuln-db/high/vote.md
          - Token URI Hijacking: vuln-db/high/Token-URI.md
          - ABI encodePacked: vuln-db/high/ABI.md
          - Gelato Unprotected: vuln-db/high/Gelato-Unprotected.md 
          - Miner Extractable Value: vuln-db/high/Miner-Extractable.md
          - Sandwich Attack: vuln-db/high/Sandwich-Attack.md
          - Signature Malleability: vuln-db/high/Signature-Malleability.md
          - ERC4626 Calculation Bugs: vuln-db/high/ERC4626.md
          - ERC721 Unsafe Minting: vuln-db/high/ERC721-unsafe-minting.md
          - Oracle Liveness Drift: vuln-db/high/Oracle-Liveness-Drift.md
          - Unbounded Proposal Gas: vuln-db/high/Unbounded-Proposal-Gas.md
          - Imbalanced Liquidity: vuln-db/high/Imbalanced-Liquidity.md
          - Missing Input Validation: vuln-db/high/Missing-Input-Validation.md
          - Inflation Amplification: vuln-db/high/Inflation-Amplification.md
          - Permit Replay Across: vuln-db/high/Permit-Replay-Across.md
          - Malicious Third-Party Vulnerabilities: vuln-db/high/Malicious-Third-Party.md
          - Weak Encryption: vuln-db/high/Weak-Encryption.md
          - Read-Only Reentrancy: vuln-db/high/Read-Only-Reentrancy.md
          - Transaction Ordering: vuln-db/high/Transaction-Ordering.md
          - LP Token Burn: vuln-db/high/LP-Token-Burn.md
          - Unbounded Loops: vuln-db/high/Unbounded-Loops.md
          - Token Whitelisting: vuln-db/high/Token-Whitelisting.md
          - Insufficient Fee Logic: vuln-db/high/Insufficient-Fee-Logic.md
          - Admin Key Misuse: vuln-db/high/Admin-Key-Misuse.md
          - Privileged Role Migration Loophole: vuln-db/high/Privileged.md
          - Unprotected setMintFeeRecipient: vuln-db/high/Unprotected-setMintFeeRecipient.md
          - Ignoring Chain Reorgs: vuln-db/high/Ignoring-Chain-Reorgs.md
          - Ignoring SafeERC20: vuln-db/high/Ignoring-SafeERC20.md
          - Lack of Circuit Breakers: vuln-db/high/Lack-of-Circuit-Breakers.md
          - Lack of Pausable Functionality: vuln-db/high/Lack-of-Pausable-Functionality.md
          - Logic Errors: vuln-db/high/Logic-Errors.md
          - Sybil Attack Vectors: vuln-db/high/Sybil-Attack-Vectors.md
      - Medium:
          - Overview: vuln-db/medium/index.md
          - Fallback-Function-Misuse: vuln-db/medium/Fallback-Function.md
          - Gas Griefing: vuln-db/medium/Gas-Griefing.md
          - Time Manipulation: vuln-db/medium/Time-Manipulation.md
          - Improper Error: vuln-db/medium/Improper-Error.md
          - Contract Size Limit: vuln-db/medium/Contract-Size-Limit.md
          - Minting to Burn: vuln-db/medium/Minting-to-Burn.md
          - Approval Reset Race Condition: vuln-db/medium/Approval-Reset-Race.md
          - Bribery: vuln-db/medium/Bribery.md
          - Zero Fee Manipulation: vuln-db/medium/Zero-Fee.md
          - Off-by-One Errors: vuln-db/medium/Off-by-One.md
          - Modifying Storage: vuln-db/medium/Modifying.md
          - Name Reuse: vuln-db/medium/Name-Reuse.md
          - Public Mappings: vuln-db/medium/Public-Mappings.md
          - Dangerous Strict Equalities: vuln-db/medium/Dangerous-Strict-Equalities.md
          - Contracts That Lock Ether: vuln-db/medium/Contracts.md
          - Dangerous Unary Expressions: vuln-db/medium/Dangerous-Unary-Expressions.md
          - Unimplemented Functions: vuln-db/medium/Unimplemented-Functions.md
          - Shadow Fork Confusion: vuln-db/medium/Shadow-Fork.md
          - State Leakage: vuln-db/medium/State-Leakage.md
          - Missing Fallback Gas: vuln-db/medium/Missing-Fallback-Gas.md
          - Precision Loss: vuln-db/medium/Precision-Loss.md
          - Force-Feeding Attacks: vuln-db/medium/Force-Feeding-Attacks.md
          - Early Claiming: vuln-db/medium/Early-Claiming.md
          - Incentive Misalignment: vuln-db/medium/Incentive-Misalignment.md
          - Reward Accumulator Drift: vuln-db/medium/Reward-Accumulator-Drift.md
          - Recursive Internal: vuln-db/medium/Recursive-Internal.md
          - Unsafe Mint: vuln-db/medium/Unsafe-Mint.md
          - Gas Price Dependent: vuln-db/medium/Gas-Price.md
          - Mutable On-Chain Metadata: vuln-db/medium/Mutable-On-Chain.md
          - Admin Can Lock Funds: vuln-db/medium/Admin-Can-Lock-Funds.md
          - Array Length Assignment: vuln-db/medium/ArrayLength-Assignment.md
          - Conflicting Modifiers: vuln-db/medium/Conflicting-Modifiers.md
          - Dangerous Enum: vuln-db/medium/Dangerous-Enum.md
          - EmissionScheduler: vuln-db/medium/EmissionScheduler.md
          - ERC1155: vuln-db/medium/ERC1155.md
          - Excessive Gas: vuln-db/medium/Excessive-Gas.md
          - Gas Fee Arbitrage: vuln-db/medium/Gas-Fee-Arbitrage.md
          - Gasless Send: vuln-db/medium/Gasless-Send.md
          - Inconsistent ETH Handling: vuln-db/medium/Inconsistent-ETH-Handling.md
          - Inadherence to Standards: vuln-db/medium/Inadherence-to-Standards.md
          - Non-Reverting Functions: vuln-db/medium/Non-Reverting.md
          - Overlapping Function: vuln-db/medium/Overlapping-Function.md
          - NFT Royalty: vuln-db/medium/NFT-Royalty.md
          - Stuck Swap Pools: vuln-db/medium/Stuck-Swap-Pools.md
          - Token Approval: vuln-db/medium/Token-Approval.md
          - Token Migration: vuln-db/medium/Token-Migration.md
          - Unchecked transfer: vuln-db/medium/Unchecked-transfer.md
      - Low:
          - Overview: vuln-db/low/index.md
          - Gas-Inefficient: vuln-db/low/Gas-Inefficiencies-attack.md
          - Hardcoded: vuln-db/low/Hardcoded.md
          - Ambiguous Constant: vuln-db/low/Ambiguous-Constant.md
          - Incomplete Event: vuln-db/low/Incomplete-Event.md
          - Deletion on Mapping: vuln-db/low/Deletion-on-Mapping.md
          - Event Emission Flaws: vuln-db/low/Event-Emission-Flaws.md
          - Unoptimized Data Structures: vuln-db/low/Unoptimized-Data-Structures.md
      - Informational:
          - Overview: vuln-db/Informational/index.md 
          - Missing NatSpec: vuln-db/Informational/Missing-NatSpec.md
          - Redundant Code Logic: vuln-db/Informational/Redundant-Code-Logic.md
          - Tautological: vuln-db/Informational/Tautological.md
          - Unused Imports: vuln-db/Informational/Unused-Imports.md
          - Unreferenced Variables: vuln-db/Informational/Unreferenced-Variables.md
          - Ambiguous Naming: vuln-db/Informational/Ambiguous-Naming.md
          - Non-Indexed Events: vuln-db/Informational/Non-Indexed-Events.md
          - Excessive Comments: vuln-db/Informational/Excessive-Comments.md
          - Improper Function Grouping: vuln-db/Informational/Improper-Function-Grouping.md
          - Inconsistent Style: vuln-db/Informational/Inconsistent-Style.md
          - Lack of Fallback Function: vuln-db/Informational/Lack-of-Fallback-Function.md
          - Unsorted Imports: vuln-db/Informational/Unsorted-Imports.md
          - Debug Statements Left: vuln-db/Informational/Debug-Statements-Left.md
  - Hacks Database:
      - Overview: hacks-db/index.md
      - Template: hacks-db/template.md 
      - Critical:
          - Overview: hacks-db/critical/index.md
          - Alpha-Homora: hacks-db/critical/Alpha-Homora.md
          - Uranium Finance: hacks-db/critical/Uranium-Finance.md
          - Poly Network: hacks-db/critical/Poly-Network.md
          - Cream Finance: hacks-db/critical/Cream-Finance.md
          - BadgerDAO: hacks-db/critical/BadgerDAO.md
          - Wormhole: hacks-db/critical/Wormhole.md
          - Ronin Network: hacks-db/critical/Ronin-Network.md
          - Nomad Bridge: hacks-db/critical/Nomad-Bridge.md
          - BNB Chain: hacks-db/critical/BNB-Chain.md
          - Ankr Protocol: hacks-db/critical/Ankr-Protocol.md
          - TempleDAO: hacks-db/critical/TempleDAO.md
          - Transit Swap: hacks-db/critical/Transit-Swap.md
          - PancakeBunny: hacks-db/critical/PancakeBunny.md
          - Yam Finance: hacks-db/critical/Yam-Finance.md
          - Snowdog DAO: hacks-db/critical/Snowdog-DAO.md
          - Saddle Finance: hacks-db/critical/Saddle-Finance.md
          - Meerkat Finance: hacks-db/critical/Meerkat-Finance.md
          - Hundred Finance: hacks-db/critical/Hundred-Finance.md
          - LendHub: hacks-db/critical/LendHub.md
          - Linode Infrastructure: hacks-db/critical/Linode-Infrastructure.md
          - CryptoNova: hacks-db/critical/CryptoNova.md
          - Velodrome: hacks-db/critical/Velodrome.md
          - Beanstalk Protocol: hacks-db/critical/Beanstalk-Protocol.md
          - LaunchZone: hacks-db/critical/LaunchZone.md
          - Gala Games: hacks-db/critical/Gala-Games.md
          - Harmony Horizon: hacks-db/critical/Harmony-Horizon.md
          - Multichain: hacks-db/critical/Multichain.md
          - Zunami Protocol: hacks-db/critical/Zunami-Protocol.md
          - Exactly Protocol: hacks-db/critical/Exactly-Protocol.md
          - Galxe: hacks-db/critical/Galxe.md
          - Arcadia Finance: hacks-db/critical/Arcadia-Finance.md
          - Sturdy Finance: hacks-db/critical/Sturdy-Finance.md
          - Curve Finance:  hacks-db/critical/Curve-Finance.md
          - Balancer Frontend: hacks-db/critical/Balancer-Frontend.md
          - Velocore: hacks-db/critical/Velocore.md
          - zkSync: hacks-db/critical/zkSync.md
          - Merlin DEX: hacks-db/critical/Merlin-DEX.md 
          - Kokomo Finance: hacks-db/critical/Kokomo-Finance.md
          - Defrost Finance: hacks-db/critical/Defrost-Finance.md
          - Onyx Protocol: hacks-db/critical/Onyx-Protocol.md
          - Radiant Capital: hacks-db/critical/Radiant-Capital.md
          - Sonne Finance: hacks-db/critical/Sonne-Finance.md
          - Dolomite: hacks-db/critical/Dolomite.md
          - Orbit Bridge: hacks-db/critical/Orbit-Bridge.md
          - Super Sushi: hacks-db/critical/Super-Sushi.md
          - KyberSwap Elastic: hacks-db/critical/KyberSwap-Elastic.md
          - THORChain: hacks-db/critical/THORChain.md
          - LeetSwap: hacks-db/critical/LeetSwap.md
          - KiloEx: hacks-db/critical/KiloEx.md
          - El Dorado: hacks-db/critical/El-Dorado.md
          - Euler Finance: hacks-db/critical/Euler-Finance.md
          - dForce Lendf:  hacks-db/critical/dForce-Lendf.md
          - WOOFi: hacks-db/critical/WOOFi.md
          - Convergence Finance: hacks-db/critical/Convergence-Finance.md
          - Eminence Finance: hacks-db/critical/Eminence-Finance.md
          - vETH Token: hacks-db/critical/vETH-Token.md
          - Curio: hacks-db/critical/Curio.md
          - Yearn Finance: hacks-db/critical/Yearn-Finance.md
          - DAO: hacks-db/critical/DAO.md
          - Parity Multisig Wallet: hacks-db/critical/Parity-Multisig-Wallet.md
          - Synthetix: hacks-db/critical/Synthetix.md
          - Uniswap v1: hacks-db/critical/Uniswap-v1.md
          - Harvest Finance: hacks-db/critical/Harvest-Finance.md
          - Inverse Finance: hacks-db/critical/Inverse-Finance.md
          - Belt Finance: hacks-db/critical/Belt-Finance.md
          - StableMagnet: hacks-db/critical/StableMagnet.md
          - Rari Capital: hacks-db/critical/Rari-Capital.md
          - EtherDelta: hacks-db/critical/EtherDelta.md
          - CoinDash: hacks-db/critical/CoinDash.md
          - Veritaseum: hacks-db/critical/Veritaseum.md
          - Cryptopia Exchange: hacks-db/critical/Cryptopia-Exchange.md
          - EXMO Exchange: hacks-db/critical/EXMO-Exchange.md
          - KuCoin Exchange: hacks-db/critical/KuCoin-Exchange.md
          - Zoth: hacks-db/critical/Zoth.md
          - Wemix: hacks-db/critical/Wemix.md
          - Cetus: hacks-db/critical/Cetus.md
          - Wintermute: hacks-db/critical/Wintermute.md
          - FTX: hacks-db/critical/FTX.md
          - Vee Finance: hacks-db/critical/Vee-Finance.md
          - Vulcan Forged: hacks-db/critical/Vulcan-Forged.md
          - Qubit Finance: hacks-db/critical/Qubit-Finance.md
          - Spartan Protocol: hacks-db/critical/Spartan-Protocol.md
          - Swerve Finance: hacks-db/critical/Swerve-Finance.md
          - Zaif Exchange: hacks-db/critical/Zaif Exchange.md 
      - High:
          - Overview: hacks-db/high/index.md
          - Reflexer Finance: hacks-db/high/Reflexer-Finance.md
          - ParaSwap: hacks-db/high/ParaSwap.md
          - Blur NFT: hacks-db/high/Blur-NFT.md
          - Raccoon Stealer: hacks-db/high/Raccoon-Stealer.md
          - LayerZero: hacks-db/high/LayerZero.md
          - BeautyChain: hacks-db/high/BeautyChain.md
          - Opyn: hacks-db/high/Opyn.md
          - DODO: hacks-db/high/DODO.md
          - Akropolis: hacks-db/high/Akropolis.md
          - bZx Oracle: hacks-db/high/bZx-Oracle.md
          - Bogged Finance: hacks-db/high/Bogged-Finance.md
          - KingDice: hacks-db/high/KingDice.md
          - SpankChain: hacks-db/high/SpankChain.md
      - Medium:
          - Overview: hacks-db/Medium/index.md
          - Kelp DAO: hacks-db/Medium/Kelp-DAO.md
          - Hegic: hacks-db/Medium/Hegic.md
          - Golem Network: hacks-db/Medium/Golem-Network.md
  - Contributing Guide: contributing/index.md
plugins:
  - search:
      separator: '[\s\-\.]+'
      lang: en
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - offline:
      enabled: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lancershield
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/lancer-shield
  generator: false
  git:
    show_revision_date: true
    show_revision_author: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - markdown.extensions.abbr
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2025 <a href="https://github.com/lancershield"  target="_blank" rel="noopener">Lancer Shield</a>
