site_name: Lancer Shield Docs
site_url: https://lancershield.github.io/docs/
strict: true
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en
  # Remove comments above palette blocks
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Overview: index.md
  - Severity Framework: severity-framework/index.md
  - Vulnerability Database:
      - Overview: vuln-db/index.md
      - Template: vuln-db/template.md
      - Critical:
          - Overview: vuln-db/critical/index.md
          - Price-Oracle: vuln-db/critical/Price-oracle.md
          - Flash-Loan-Attack: vuln-db/critical/Flash-Loan-Attacks.md
          - Arbitrary Storage: vuln-db/critical/Arbitrary-Storage.md
          - Improperly Initialized: vuln-db/critical/Improperly-Initialized.md
          - Liquidity Rug: vuln-db/critical/Liquidity-Rug.md
          - Treasury Drain: vuln-db/critical/Treasury-Drain.md
          - Backdoor Functionality: vuln-db/critical/Backdoor-Functionality.md
          - Untrusted delegatecall: vuln-db/critical/Untrusted-delegatecall.md
          - Classic Reentrancy: vuln-db/critical/Classic-Reentrancy.md
          - Contract Destructible: vuln-db/critical/Contract-Destructible.md
          - Batch Reentrancy: vuln-db/critical/Batch-Reentrancy.md
          - LayerZero Trusted: vuln-db/critical/LayerZero-Trusted.md
          - Unintended Reentrancy: vuln-db/critical/Unintended-Reentrancy.md
          - Insecure executeTransaction: vuln-db/critical/Insecure-executeTransaction.md
          - Unrestricted Withdrawals: vuln-db/critical/Unrestricted-Withdrawals.md
          - Access Control: vuln-db/critical/Access-Control.md
          - Arbitrary from in transferFrom: vuln-db/critical/Arbitrary-from.md
          - Insufficient Signature Verification: vuln-db/critical/Insufficient.md
          - Misconfigured Role-Based: vuln-db/critical/Misconfigured.md
          - Oracle Feed Delay Exploits: vuln-db/critical/Oracle-Feed-Delay-Exploits.md
      - High:
          - Overview: vuln-db/high/index.md
          - Denial of Service: vuln-db/high/denial-of-service.md
          - Improper-Upgrade: vuln-db/high/Improper-Upgradeability.md
          - Insecure-Randomness: vuln-db/high/Insecure-Randomness.md
          - Gas-Limit: vuln-db/high/Gas-Limit.md
          - Ownership-Vulnerability: vuln-db/high/Ownership.md
          - Cross-Contract: vuln-db/high/cross-contract.md
          - Blockhash Dependence: vuln-db/high/Blockhash-Dependence.md
          - merkle-proof: vuln-db/high/Merkle-proof.md
          - Async Withdraw: vuln-db/high/Async Withdraw.md
          - Reward Inflation: vuln-db/high/Reward Inflation.md
          - Upgrade Bricking: vuln-db/high/Upgrade-Bricking.md
          - Emergency Function Abuse: vuln-db/high/Emergency-Function-Abuse.md
          - Internal Accounting Drift: vuln-db/high/Internal-Accounting-Drif.md
          - Faulty Permit: vuln-db/high/Faulty-Permit.md
          - Counter Overflow: vuln-db/high/Counter-Overflow.md
          - Stale Price: vuln-db/high/Stale-Price.md
          - Unsafe tx.origin: vuln-db/high/Unsafe-tx.origin.md
          - Unchecked Slippage: vuln-db/high/Unchecked-Slippage.md
          - Ignoring ChainID: vuln-db/high/Ignoring-ChainID.md
          - Transfer Hook Abuse: vuln-db/high/Transfer-Hook-Abuse.md
          - Flawed Migration: vuln-db/high/Flawed-Migration.md
          - Front-Running NFT: vuln-db/high/Front-Running-NFT.md
          - NFT Metadata Tampering: vuln-db/high/NFT-Metadata-Tampering.md
          - Vesting Shortcut Exploits: vuln-db/high/Vesting.md
          - Flawed Slashing: vuln-db/high/Flawed-Slashing.md
          - Whitelist Bypass: vuln-db/high/Whitelist-Bypass.md
          - Unsustainable Pump and Dump: vuln-db/high/Unsustainable.md
          - Vote Escrow Exploits: vuln-db/high/vote.md
          - Token URI Hijacking: vuln-db/high/Token-URI.md
          - ABI encodePacked: vuln-db/high/ABI.md
          - Uninitialized State Variables: vuln-db/high/Uninitialized-State-Variables.md 
          - Gelato Unprotected: vuln-db/high/Gelato-Unprotected.md 
          - Miner Extractable Value: vuln-db/high/Miner-Extractable.md
          - Sandwich Attack: vuln-db/high/Sandwich-Attack.md
          - Signature Malleability: vuln-db/high/Signature-Malleability.md
          - ERC4626 Calculation Bugs: vuln-db/high/ERC4626.md
          - ERC721 Unsafe Minting: vuln-db/high/ERC721-unsafe-minting.md
          - Oracle Liveness Drift: vuln-db/high/Oracle-Liveness-Drift.md
          - Unbounded Proposal Gas: vuln-db/high/Unbounded-Proposal-Gas.md
          - Imbalanced Liquidity: vuln-db/high/Imbalanced-Liquidity.md
          - Missing Input Validation: vuln-db/high/Missing-Input-Validation.md
          - Inflation Amplification: vuln-db/high/Inflation-Amplification.md
          - Permit Replay Across: vuln-db/high/Permit-Replay-Across.md
          - Malicious Third-Party Vulnerabilities: vuln-db/high/Malicious-Third-Party.md
          - Weak Encryption: vuln-db/high/Weak-Encryption.md
          - Read-Only Reentrancy: vuln-db/high/Read-Only-Reentrancy.md
          - Transaction Ordering: vuln-db/high/Transaction-Ordering.md
          - LP Token Burn: vuln-db/high/LP-Token-Burn.md
          - Unbounded Loops: vuln-db/high/Unbounded-Loops.md
          - Token Whitelisting: vuln-db/high/Token-Whitelisting.md
          - Insufficient Fee Logic: vuln-db/high/Insufficient-Fee-Logic.md
          - Admin Key Misuse: vuln-db/high/Admin-Key-Misuse.md
          - Privileged Role Migration Loophole: vuln-db/high/Privileged.md
          - Unprotected setMintFeeRecipient: vuln-db/high/Unprotected-setMintFeeRecipient.md
          - Ignoring Chain Reorgs: vuln-db/high/Ignoring-Chain-Reorgs.md
          - Ignoring SafeERC20: vuln-db/high/Ignoring-SafeERC20.md
          - Lack of Circuit Breakers: vuln-db/high/Lack-of-Circuit-Breakers.md
          - Lack of Pausable Functionality: vuln-db/high/Lack-of-Pausable-Functionality.md
          - Logic Errors: vuln-db/high/Logic-Errors.md
          - Sybil Attack Vectors: vuln-db/high/Sybil-Attack-Vectors.md
      - Medium:
          - Overview: vuln-db/medium/index.md
          - Fallback-Function-Misuse: vuln-db/medium/Fallback-Function.md
          - Gas Griefing: vuln-db/medium/Gas-Griefing.md
          - Time Manipulation: vuln-db/medium/Time-Manipulation.md
          - Improper Error: vuln-db/medium/Improper-Error.md
          - Contract Size Limit: vuln-db/medium/Contract-Size-Limit.md
          - Minting to Burn: vuln-db/medium/Minting-to-Burn.md
          - Approval Reset Race Condition: vuln-db/medium/Approval-Reset-Race.md
          - Bribery: vuln-db/medium/Bribery.md
          - Zero Fee Manipulation: vuln-db/medium/Zero-Fee.md
          - Off-by-One Errors: vuln-db/medium/Off-by-One.md
          - Modifying Storage: vuln-db/medium/Modifying.md
          - Name Reuse: vuln-db/medium/Name-Reuse.md
          - Public Mappings: vuln-db/medium/Public-Mappings.md
          - Dangerous Strict Equalities: vuln-db/medium/Dangerous-Strict-Equalities.md
          - Contracts That Lock Ether: vuln-db/medium/Contracts.md
          - Dangerous Unary Expressions: vuln-db/medium/Dangerous-Unary-Expressions.md
          - Unimplemented Functions: vuln-db/medium/Unimplemented-Functions.md
          - Shadow Fork Confusion: vuln-db/medium/Shadow-Fork.md
          - State Leakage: vuln-db/medium/State-Leakage.md
          - Missing Fallback Gas: vuln-db/medium/Missing-Fallback-Gas.md
          - Precision Loss: vuln-db/medium/Precision-Loss.md
          - Force-Feeding Attacks: vuln-db/medium/Force-Feeding-Attacks.md
          - Early Claiming: vuln-db/medium/Early-Claiming.md
          - Incentive Misalignment: vuln-db/medium/Incentive-Misalignment.md
          - Reward Accumulator Drift: vuln-db/medium/Reward-Accumulator-Drift.md
          - Recursive Internal: vuln-db/medium/Recursive-Internal.md
          - Unsafe Mint: vuln-db/medium/Unsafe-Mint.md
          - Gas Price Dependent: vuln-db/medium/Gas-Price.md
          - Mutable On-Chain Metadata: vuln-db/medium/Mutable-On-Chain.md
          - Admin Can Lock Funds: vuln-db/medium/Admin-Can-Lock-Funds.md
          - Array Length Assignment: vuln-db/medium/ArrayLength-Assignment.md
          - Conflicting Modifiers: vuln-db/medium/Conflicting-Modifiers.md
          - Dangerous Enum: vuln-db/medium/Dangerous-Enum.md
          - EmissionScheduler: vuln-db/medium/EmissionScheduler.md
          - ERC1155: vuln-db/medium/ERC1155.md
          - Excessive Gas: vuln-db/medium/Excessive-Gas.md
          - Gas Fee Arbitrage: vuln-db/medium/Gas-Fee-Arbitrage.md
          - Gasless Send: vuln-db/medium/Gasless-Send.md
          - Inconsistent ETH Handling: vuln-db/medium/Inconsistent-ETH-Handling.md
          - Inadherence to Standards: vuln-db/medium/Inadherence-to-Standards.md
          - Non-Reverting Functions: vuln-db/medium/Non-Reverting.md
          - Overlapping Function: vuln-db/medium/Overlapping-Function.md
          - NFT Royalty: vuln-db/medium/NFT-Royalty.md
          - Stuck Swap Pools: vuln-db/medium/Stuck-Swap-Pools.md
          - Token Approval: vuln-db/medium/Token-Approval.md
          - Token Migration: vuln-db/medium/Token-Migration.md
          - Unchecked transfer: vuln-db/medium/Unchecked-transfer.md
      - Low:
          - Overview: vuln-db/low/index.md
          - Gas-Inefficient: vuln-db/low/Gas-Inefficiencies-attack.md
          - Hardcoded: vuln-db/low/Hardcoded.md
          - Ambiguous Constant: vuln-db/low/Ambiguous-Constant.md
          - Incomplete Event: vuln-db/low/Incomplete-Event.md
          - Deletion on Mapping: vuln-db/low/Deletion-on-Mapping.md
          - Event Emission Flaws: vuln-db/low/Event-Emission-Flaws.md
          - Unoptimized Data Structures: vuln-db/low/Unoptimized-Data-Structures.md
      - Informational:
          - Overview: vuln-db/Informational/index.md 
          - Missing NatSpec: vuln-db/Informational/Missing-NatSpec.md
          - Redundant Code Logic: vuln-db/Informational/Redundant-Code-Logic.md
          - Tautological: vuln-db/Informational/Tautological.md
  - Contributing Guide: contributing/index.md

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang: en
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - offline:
      enabled: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lancershield
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/lancer-shield
  generator: false
  git:
    show_revision_date: true
    show_revision_author: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - markdown.extensions.abbr
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2025 <a href="https://github.com/lancershield"  target="_blank" rel="noopener">Lancer Shield</a>
