site_name: Lancer Shield Docs
site_url: https://lancershield.github.io/docs/
strict: true
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en
  # Remove comments above palette blocks
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Overview: index.md
  - Severity Framework: severity-framework/index.md
  - Vulnerability Database:
      - Overview: vuln-db/index.md
      - Template: vuln-db/template.md
      - Critical:
          - Overview: vuln-db/critical/index.md
          - Price-Oracle: vuln-db/critical/Price-oracle.md
          - Flash-Loan-Attack: vuln-db/critical/Flash-Loan-Attacks.md
          - Arbitrary Storage: vuln-db/critical/Arbitrary-Storage.md
          - Improperly Initialized: vuln-db/critical/Improperly-Initialized.md
          - Admin Key Misuse: vuln-db/critical/Admin-Key-Misuse.md
          - Unverified Upgrade: vuln-db/critical/Unverified-Upgrade.md
          - Liquidity Rug: vuln-db/critical/Liquidity-Rug.md
          - Treasury Drain: vuln-db/critical/Treasury-Drain.md
          - Backdoor Functionality: vuln-db/critical/Backdoor-Functionality.md
          - Untrusted delegatecall: vuln-db/critical/Untrusted-delegatecall.md
          - Classic Reentrancy: vuln-db/critical/Classic-Reentrancy.md
          - Contract Destructible: vuln-db/critical/Contract-Destructible.md
          - Privileged Role Migration Loophole: vuln-db/critical/Privileged.md
          - Overlapping Function: vuln-db/critical/Overlapping-Function.md
          - Batch Reentrancy: vuln-db/critical/Batch-Reentrancy.md
          - Flashloan-Reentrancy: vuln-db/critical/Flashloan-Reentrancy.md
          - LayerZero Trusted: vuln-db/critical/LayerZero-Trusted.md
      - High:
          - Overview: vuln-db/high/index.md
          - Denial of Service: vuln-db/high/denial-of-service.md
          - Access Control: vuln-db/high/Access-control.md
          - Reentrancy: vuln-db/high/Reentrancy.md
          - Integer-Overflow: vuln-db/high/Integer-Overflow.md
          - Improper-Upgrade: vuln-db/high/Improper-Upgradeability.md
          - Insecure-Randomness: vuln-db/high/Insecure-Randomness.md
          - Gas-Limit: vuln-db/high/Gas-Limit.md
          - Ownership-Vulnerability: vuln-db/high/Ownership.md
          - Insufficient-Signature-Verification: vuln-db/high/Insufficient.md
          - Cross-Contract: vuln-db/high/cross-contract.md
          - Uninitialized-Storage: vuln-db/high/Uninitialized-Storage.md
          - Selfdestruct: vuln-db/high/Selfdestruct.md
          - Signature Replay: vuln-db/high/Signature-Replay.md
          - Blockhash Dependence: vuln-db/high/Blockhash-Dependence.md
          - Proxy Pattern: vuln-db/high/Proxy-Pattern.md
          - merkle-proof: vuln-db/high/Merkle-proof.md
          - Async Withdraw: vuln-db/high/Async Withdraw.md
          - Reward Inflation: vuln-db/high/Reward Inflation.md
          - Upgrade Bricking: vuln-db/high/Upgrade-Bricking.md
          - Emergency Function Abuse: vuln-db/high/Emergency-Function-Abuse.md
          - Internal Accounting Drift: vuln-db/high/Internal-Accounting-Drif.md
          - Delegatecall: vuln-db/high/Delegatecall.md
          - User-Defined: vuln-db/high/User-Defined.md
          - Math Underflow: vuln-db/high/Math-Underflow.md
          - Faulty Permit: vuln-db/high/Faulty-Permit.md
          - Oracle Feed Delay: vuln-db/high/Oracle-Feed-Delay.md
          - Counter Overflow: vuln-db/high/Counter-Overflow.md
          - Reused Hash Collision: vuln-db/high/Reused-Hash-Collision.md
          - Stale Price: vuln-db/high/Stale-Price.md
          - Missing Nonce Checks: vuln-db/high/Missing-Nonce-Checks.md
          - Unsafe tx.origin: vuln-db/high/Unsafe-tx.origin.md
          - Unchecked Slippage: vuln-db/high/Unchecked-Slippage.md
          - Token Approval: vuln-db/high/Token-Approval.md
          - Token Migration: vuln-db/high/Token-Migration.md
          - Ignoring ChainID: vuln-db/high/Ignoring-ChainID.md
          - Contract Address Collision: vuln-db/high/Contract-Address-Collision.md
          - Transfer Hook Abuse: vuln-db/high/Transfer-Hook-Abuse.md
          - Flawed Migration: vuln-db/high/Flawed-Migration.md
          - Front-Running NFT: vuln-db/high/Front-Running-NFT.md
          - NFT Metadata Tampering: vuln-db/high/NFT-Metadata-Tampering.md
          - Vesting Shortcut Exploits: vuln-db/high/Vesting.md
          - Flawed Slashing: vuln-db/high/Flawed-Slashing.md
          - Stuck Swap Pools: vuln-db/high/Stuck-Swap-Pools.md
          - Gas Bombs: vuln-db/high/Gas-Bombs.md
          - Whitelist Bypass: vuln-db/high/Whitelist-Bypass.md
          - NFT Royalty Bypass: vuln-db/high/Royalty-Bypass.md
          - Misconfigured Role-Based: vuln-db/high/Misconfigured-Role-Based.md
          - Unsustainable Pump and Dump: vuln-db/high/Unsustainable.md
          - Vote Escrow Exploits: vuln-db/high/vote.md
          - Token URI Hijacking: vuln-db/high/Token-URI.md
          - Storage ABIEncoderV2: vuln-db/high/Storage.md
          - Arbitrary from in transferFrom: vuln-db/high/Arbitrary-from.md
          - ABI encodePacked: vuln-db/high/ABI.md
          - Incorrect Shift: vuln-db/high/Incorrect-shift.md
          - Multiple Constructor: vuln-db/high/Multiple.md
          - Protected Variables: vuln-db/high/Protected-Variables.md
          - Right-to-Left: vuln-db/high/Right-to-Left.md
          - Uninitialized State Variables: vuln-db/high/Uninitialized-State-Variables.md
          - Array Length Assignment: vuln-db/high/ArrayLength-Assignment.md
          - Incorrect Exponentiation: vuln-db/high/Incorrect-Exponentiation.md
          - Incorrect Return: vuln-db/high/Incorrect-Return.md
          - Unchecked transfer: vuln-db/high/Unchecked-transfer.md
          - Weak PRNG: vuln-db/high/Weak-PRNG.md
          - Codex Pattern: vuln-db/high/Codex-Pattern.md
          - Domain Separator Collision: vuln-db/high/Domain-Separator.md
          - Dangerous Enum: vuln-db/high/Dangerous-Enum.md
          - Incorrect ERC-20: vuln-db/high/Incorrect-ERC-20.md
          - Incorrect ERC-721: vuln-db/high/Incorrect-ERC-721.md
          - Deprecated Pyth Functions: vuln-db/high/Pyth-Functions.md
          - Chronicle Unchecked Price: vuln-db/high/Chronicle-Unchecked.md  
          - Gelato Unprotected: vuln-db/high/Gelato-Unprotected.md 
          - Out-of-Order: vuln-db/high/Out-of-Order.md
          - Chainlink Feed Registry: vuln-db/high/Chainlink-Feed-Registry.md
          - Deprecated Optimism: vuln-db/high/Optimism-deprecated.md
          - Void Constructor: vuln-db/high/Void-Constructor.md
          - Return Bomb: vuln-db/high/Return-Bomb.md
          - Unsafe Assembly: vuln-db/high/Unsafe-Assembly.md 
          - Gas Fee Arbitrage: vuln-db/high/Gas-Fee-Arbitrage.md
          - Unsafe Use of assert: vuln-db/high/Unsafe-Use-of-assert.md
          - Miner Extractable Value: vuln-db/high/Miner-Extractable.md
          - Sandwich Attack: vuln-db/high/Sandwich-Attack.md
          - Unexpected Contract: vuln-db/high/Unexpected-Contract.md
          - Conflicting Modifiers: vuln-db/high/Conflicting-Modifiers.md
          - Signature Malleability: vuln-db/high/Signature-Malleability.md
          - ERC4626 Calculation Bugs: vuln-db/high/ERC4626.md
          - ERC1155 Unsafe BatchTransfer: vuln-db/high/ERC1155.md
          - ERC721 Unsafe Minting: vuln-db/high/ERC721-unsafe-minting.md
          - Non-Reverting: vuln-db/high/Non-Reverting.md
          - Oracle Liveness Drift: vuln-db/high/Oracle-Liveness-Drift.md
          - Unbounded Proposal Gas: vuln-db/high/Unbounded-Proposal-Gas.md
          - Imbalanced Liquidity: vuln-db/high/Imbalanced-Liquidity.md
      - Medium:
          - Overview: vuln-db/medium/index.md
          - logical-errors: vuln-db/medium/logic-errors.md
          - Timestamp-Dependence: vuln-db/medium/Timestamp-dependency.md
          - Fallback-Function-Misuse: vuln-db/medium/Fallback-Function.md
          - Gas Griefing: vuln-db/medium/Gas-Griefing.md
          - Time Manipulation: vuln-db/medium/Time-Manipulation.md
          - Event Emission: vuln-db/medium/Event-Emission.md
          - Improper Error: vuln-db/medium/Improper-Error.md
          - Contract Size Limit: vuln-db/medium/Contract-Size-Limit.md
          - Unused Modifiers: vuln-db/medium/Unused-Modifiers.md
          - Deprecated Solidity: vuln-db/medium/Deprecated-Solidity.md
          - Overuse of Inline: vuln-db/medium/Overuse-of-Inline.md
          - Lack of Circuit Breakers: vuln-db/medium/Lack-of-Circuit-Breakers.md
          - Unoptimized Data: vuln-db/medium/Unoptimized.md
          - Ignoring Chain: vuln-db/medium/Ignoring-Chain.md
          - Inconsistent Decimal: vuln-db/medium/Inconsistent-Decimal.md
          - Ignoring SafeERC20: vuln-db/medium/Ignoring-SafeERC20.md
          - Minting to Burn: vuln-db/medium/Minting-to-Burn.md
          - Approval Reset Race Condition: vuln-db/medium/Approval-Reset-Race.md
          - Gas Token Exploitation: vuln-db/medium/Gas-Token-Exploitation.md
          - Broken Interface: vuln-db/medium/Broken-Interface.md
          - Bribery: vuln-db/medium/Bribery.md
          - Zero Fee Manipulation: vuln-db/medium/Zero-Fee.md
          - Off-by-One Errors: vuln-db/medium/Off-by-One.md
          - Modifying Storage: vuln-db/medium/Modifying.md
          - Name Reuse: vuln-db/medium/Name-Reuse.md
          - Public Mappings: vuln-db/medium/Public-Mappings.md
          - Storage Signed: vuln-db/medium/Storage-Signed.md
          - Dangerous Strict Equalities: vuln-db/medium/Dangerous-Strict-Equalities.md
          - Contracts That Lock Ether: vuln-db/medium/Contracts.md
          - Deletion on Mapping: vuln-db/medium/Deletion-on-Mapping.md
          - Unchecked send: vuln-db/medium/Unchecked-send.md
          - Missing Events: vuln-db/medium/Missing-Events.md
          - Dangerous Unary Expressions: vuln-db/medium/Dangerous-Unary-Expressions.md
          - Block timestamp: vuln-db/medium/block-timestamp.md
          - Unimplemented Functions: vuln-db/medium/Unimplemented-Functions.md
          - Lack of Pausable: vuln-db/medium/Lack-of-Pausable.md
          - Shadow Fork Confusion: vuln-db/medium/Shadow-Fork.md
          - State Leakage: vuln-db/medium/State-Leakage.md
          - Empty catch Blocks: vuln-db/medium/Empty-catch-blocks.md
          - Boolean Short-Circuit: vuln-db/medium/Boolean-Short-Circuit.md
          - Missing Fallback Gas: vuln-db/medium/Missing-Fallback-Gas.md
      - Low:
          - Overview: vuln-db/low/index.md
          - Gas-Inefficient: vuln-db/low/Gas-Inefficiencies-attack.md
          - Redundant Code Logic: vuln-db/low/Redundant-Code-Logic.md
          - Missing Events: vuln-db/low/Missing-Events.md
          - Hardcoded: vuln-db/low/Hardcoded.md
          - Incomplete Event Logging: vuln-db/low/Incomplete-Event.md
          - Tautological: vuln-db/low/Tautological.md
          - Builtin Symbol Shadowing: vuln-db/low/Builtin-Symbol-Shadowing.md
          - Ambiguous Constant: vuln-db/low/Ambiguous-Constant.md
          - Missing NatSpec: vuln-db/low/Missing-NatSpec.md
  - Contributing Guide: contributing/index.md

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang: en
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - offline:
      enabled: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lancershield
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/lancer-shield
  generator: false
  git:
    show_revision_date: true
    show_revision_author: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - markdown.extensions.abbr
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2025 <a href="https://github.com/lancershield"  target="_blank" rel="noopener">Lancer Shield</a>
