site_name: Lancer-shield-docs
site_url: https://lancershield.github.io/docs/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en
  # Remove comments above palette blocks
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Overview: index.md
  - Severity Framework: severity-framework/index.md
  - Vulnerability Database:
      - Overview: vuln-db/index.md
      - Template: vuln-db/template.md
      - Critical:
          - Overview: vuln-db/critical/Overview.md
          - Price-Oracle: vuln-db/critical/Price-oracle.md
          - Flash-Loan-Attack: vuln-db/critical/Flash-Loan-Attacks.md
          - Arbitrary Storage: vuln-db/critical/Arbitrary-Storage.md
          - Improperly Initialized: vuln-db/critical/Improperly-Initialized.md
          - Admin Key Misuse : vuln-db/critical/Admin-Key-Misuse.md
          - Unverified Upgrade: vuln-db/critical/Unverified-Upgrade.md
          - Liquidity Rug: vuln-db/critical/Liquidity-Rug.md
      - high:  
          - Overview: vuln-db/high/Overview.md
          - Denial of Service: vuln-db/high/denial-of-service.md
          - Access Control: vuln-db/high/Access-control.md
          - Reentrancy: vuln-db/high/Reentrancy.md
          - Integer-Overflow: vuln-db/high/Integer-Overflow.md
          - Improper-Upgrade: vuln-db/high/Improper-Upgradeability.md
          - Insecure-Randomness: vuln-db/high/Insecure-Randomness.md
          - Gas-Limit: vuln-db/high/Gas-Limit.md
          - Ownership-Vulnerability: vuln-db/high/Ownership.md
          - Insufficient-Signature-Verification: vuln-db/high/Insufficient.md
          - Cross-Contract : vuln-db/high/cross-contract.md
          - Uninitialized-Storage: vuln-db/high/Uninitialized-Storage.md
          - Selfdestruct: vuln-db/high/Selfdestruct.md
          - Signature Replay: vuln-db/high/Signature-Replay.md
          - Blockhash Dependence: vuln-db/high/Blockhash-Dependence.md
          - Proxy Pattern: vuln-db/high/Proxy-Pattern.md
          - merkle-proof: vuln-db/high/Merkle-proof.md
          - Async Withdraw: vuln-db/high/Async Withdraw.md
          - Reward Inflation: vuln-db/high/Reward Inflation.md
          - Upgrade Bricking: vuln-db/high/Upgrade-Bricking.md
          - Emergency Function Abuse: vuln-db/high/Emergency-Function-Abuse.md
          - Internal Accounting Drift: vuln-db/high/Internal-Accounting-Drif.md
          - Delegatecall: vuln-db/high/Delegatecall.md
          - User-Defined: vuln-db/high/User-Defined.md
          - Math Underflow: vuln-db/high/Math-Underflow.md
          - Faulty Permit: vuln-db/high/Faulty-Permit.md
          - Oracle Feed Delay: vuln-db/high/Oracle-Feed-Delay.md
          - Counter Overflow: vuln-db/high/Counter-Overflow.md
          - Reused Hash Collision: vuln-db/high/Reused-Hash-Collision.md
          - Stale Price: vuln-db/high/Stale-Price.md
          - Missing Nonce Checks : vuln-db/high/Missing-Nonce-Checks.md
          - Unsafe tx.origin: vuln-db/high/Unsafe-tx.origin.md
          - Unchecked Slippage: vuln-db/high/Unchecked-Slippage.md
          - Token Approval: vuln-db/high/Token-Approval.md
          - Token Migration: vuln-db/high/Token-Migration.md
          - Ignoring ChainID : vuln-db/high/Ignoring-ChainID.md
          - Contract Address Collision: vuln-db/high/Contract-Address-Collision.md
          - Transfer Hook Abuse : vuln-db/high/Transfer-Hook-Abuse.md
          - Flawed Migration: vuln-db/high/Flawed-Migration.md
          - Front-Running NFT: vuln-db/high/Front-Running-NFT.md
          - NFT Metadata Tampering : vuln-db/high/NFT-Metadata-Tampering.md
          - Vesting Shortcut Exploits : vuln-db/high/Vesting.md
          - Flawed Slashing: vuln-db/high/Flawed-Slashing.md
          - Stuck Swap Pools : vuln-db/high/Stuck-Swap-Pools.md
    
      - medium:
          - Overview: vuln-db/medium/Overview.md
          - logical-errors: vuln-db/medium/logic-errors.md
          - Timestamp-Dependence: vuln-db/medium/Timestamp-dependency.md
          - Fallback-Function-Misuse: vuln-db/medium/Fallback-Function.md
          - Gas Griefing: vuln-db/medium/Gas-Griefing.md
          - Time Manipulation : vuln-db/medium/Time-Manipulation.md
          - Event Emission: vuln-db/medium/Event-Emission.md
          - Improper Error: vuln-db/medium/Improper-Error.md
          - Contract Size Limit: vuln-db/medium/Contract-Size-Limit.md
          - Unused Modifiers: vuln-db/medium/Unused-Modifiers.md
          - Deprecated Solidity: vuln-db/medium/Deprecated-Solidity.md
          - Overuse of Inline: vuln-db/medium/Overuse-of-Inline.md
          - Lack of Circuit Breakers: vuln-db/medium/Lack-of-Circuit-Breakers.md
          - Unoptimized Data: vuln-db/medium/Unoptimized.md
          - Ignoring Chain: vuln-db/medium/Ignoring-Chain.md
          - Inconsistent Decimal: vuln-db/medium/Inconsistent-Decimal.md
          - Ignoring SafeERC20 : vuln-db/medium/Ignoring-SafeERC20.md
          - Minting to Burn: vuln-db/medium/Minting-to-Burn.md
          - Approval Reset Race Condition : vuln-db/medium/Approval-Reset-Race.md
          - Gas Token Exploitation : vuln-db/medium/Gas-Token-Exploitation.md
          - Broken Interface: vuln-db/medium/Broken-Interface.md
          - Bribery: vuln-db/medium/Bribery.md
          - Zero Fee Manipulation : vuln-db/medium/Zero-Fee.md


      - low: 
          - Overview: vuln-db/low/Overview.md
          - Gas-Inefficient: vuln-db/low/Gas-Inefficiencies-attack.md
          - Redundant Code Logic: vuln-db/low/Redundant-Code-Logic.md
          - Missing Events: vuln-db/low/Missing-Events.md
          - Hardcoded: vuln-db/low/Hardcoded.md
          - Incomplete Event Logging : vuln-db/low/Incomplete-Event.md

  - Contributing Guide: contributing/index.md

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lancershield
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/lancer-shield

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2025 <a href="https://github.com/lancershield"  target="_blank" rel="noopener">Lancer Shield</a>
